[package]
name = "corona-zbus-nm-secret-agent-manager"
version = "0.1.0"
repository = "https://github.com/pop-os/dbus-settings-bindings"
description = "dbus bindings for org.freedesktop.NetworkManager.AgentManager with zbus"
license = "MPL-2.0"
edition = "2024"

[lib]
name = "nm_secret_agent_manager"

[dependencies]
zbus.workspace = true
